---
chache_dir: ~/Library/Caches/battleschool

sources:

  git:
    - name: 'osx'
      repo: 'https://github.com/alexrecarey/battleschool-config.git'
      playbooks:
        - homebrew.yml          # install homebrew
        - homebrew-casks.yml    # install general GUI Apps
        - python.yml            # Setup python dev environment
