 ---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in homebrew-cask.yml playbook"

    - name: Install cask for homebrew
      homebrew: name=brew-cask state=present update_homebrew=yes
      

    - name: Install Casks from homebrew cask
      homebrew_cask: name{{item}}
      with_items:
        - google-chrome          # Browser
        - amethyst               # Tiling VM for OS X
        - bartender              # Tidy up the top icon bar
#       - usb-overdrive          # Configure USB keyboards and mice
        - telephone              # IP Phone
        - dropbox                # File sharing
        - bittorrent-sync        # File sharing peer to peer
        - telegram               # Chat client
        - onepassword            # Password manager
        - dash                   # Documentation reader
        - spotify                # Music player
        - paintcode              # SVG to Code icon drawer
        - simpholders            # Access iOS Simulator folders
        - slack                  # Chat app
        - pacifist               # Open pkg files
        - intellij-idea-ce       # IDE Community Edition
        - cleanmymac             # file cleaner / deleter
        - crashlytics            # Beta testing uploader
        - mysqlworkbench         # MySQL remote shell
        - java                   # Java VM
        - bettertouchtool        # Extra trackpad awesomeness
        - vagrant                # Virtualbox manager

