---
- hosts: workstation

  tasks:
    - name: install homebrew
      mac_pkg: pkg_type=script script_creates=/usr/local/bin/brew
               script_prefix='echo | ' script_exe=ruby
               url=https://raw.githubusercontent.com/Homebrew/install/master/install

    - name: install apps from homebrew
      homebrew: name={{item}} state=present
      with_items:
          - coreutils
          - git
          - maven
          - rbenv
          - dos2unix
          - wget
          - ctags
